/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import KoneksiDB.Global;
import KoneksiDB.JanjiDB;
import KoneksiDB.MoodDB;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Edella
 */
public class janji extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(janji.class.getName());
    private JanjiDB database_janji;
    private MoodDB database_mood;
    /**
     * Creates new form janji
     */
    public janji() {
        initComponents();
        
        database_janji = new JanjiDB();
        database_mood = new MoodDB();
        
        setUkuranLokasi();
        loadCard();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        L_Tanggal = new javax.swing.JLabel();
        P_CardFlow3 = new javax.swing.JScrollPane();
        P_CardFlow = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BTN_TambahIngatan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingetin - Janji");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(234, 227, 227));
        setFocusable(false);
        setForeground(java.awt.Color.pink);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(0, 0));

        Background.setBackground(new java.awt.Color(234, 226, 226));
        Background.setMaximumSize(new java.awt.Dimension(400, 330));
        Background.setMinimumSize(new java.awt.Dimension(400, 330));
        Background.setPreferredSize(new java.awt.Dimension(400, 330));

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout1.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout1);

        jPanel1.setMaximumSize(null);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INGETIN");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("21 Mei, 09:00");
        jLabel9.setPreferredSize(new java.awt.Dimension(260, 20));
        jPanel1.add(jLabel9);

        Navbar.add(jPanel1);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 200));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        jPanel4.setMaximumSize(new java.awt.Dimension(499, 600));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(85, 30));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        L_Tanggal.setBackground(new java.awt.Color(0, 0, 0));
        L_Tanggal.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        L_Tanggal.setForeground(new java.awt.Color(0, 0, 0));
        L_Tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Tanggal.setText("27 Mei 2026");
        jPanel4.add(L_Tanggal);

        jPanel3.add(jPanel4);

        P_CardFlow3.setBackground(new java.awt.Color(234, 226, 226));
        P_CardFlow3.setBorder(null);
        P_CardFlow3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        P_CardFlow3.setFocusable(false);
        P_CardFlow3.setHorizontalScrollBar(null);
        P_CardFlow3.setPreferredSize(new java.awt.Dimension(400, 150));

        P_CardFlow.setBackground(new java.awt.Color(234, 226, 226));
        P_CardFlow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 226, 226)));
        P_CardFlow.setMinimumSize(new java.awt.Dimension(300, 200));
        P_CardFlow.setPreferredSize(new java.awt.Dimension(300, 200));
        P_CardFlow3.setViewportView(P_CardFlow);

        jPanel3.add(P_CardFlow3);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel2.setLayout(null);

        BTN_TambahIngatan.setBackground(new java.awt.Color(255, 255, 255));
        BTN_TambahIngatan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BTN_TambahIngatan.setForeground(new java.awt.Color(0, 0, 0));
        BTN_TambahIngatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Atur Motivasi.png"))); // NOI18N
        BTN_TambahIngatan.setText("<html>Tambah Ingatan</html>");
        BTN_TambahIngatan.setToolTipText("");
        BTN_TambahIngatan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN_TambahIngatan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_TambahIngatan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_TambahIngatan.addActionListener(this::BTN_TambahIngatanActionPerformed);
        jPanel2.add(BTN_TambahIngatan);
        BTN_TambahIngatan.setBounds(290, 100, 98, 96);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 88));
        jLabel4.setText("<html> \nAyo tambah ingatan \ndan setel alarmnya!! </html>");
        jLabel4.setAlignmentY(0.1F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMinimumSize(new java.awt.Dimension(270, 21));
        jLabel4.setRequestFocusEnabled(false);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 20, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/IMG_Bubble3.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 10, 139, 75);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/IMG_Janji.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 144, 144);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Atur Motivasi.png"))); // NOI18N
        jButton2.setText("<html>Setel Alarm</html>");
        jButton2.setToolTipText("");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);
        jButton2.setBounds(190, 100, 98, 96);

        jPanel3.add(jPanel2);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BTN_TambahIngatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TambahIngatanActionPerformed
        janji_form F_JanjiForm = new janji_form();
        F_JanjiForm.setVisible(true);
    }//GEN-LAST:event_BTN_TambahIngatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new janji().setVisible(true));
    }
    
    private void loadCard() {

        ResultSet rs = database_janji.tampilJanji();
        L_Tanggal.setText(this.formatKeHariBulan(Global.tanggal));

        try {

            P_CardFlow.removeAll();

            while (rs.next()) {
                System.out.println(rs);
                System.out.println(rs.getString("appointment"));

                P_CardJanji card = new P_CardJanji();

                card.setTitle(
                    rs.getString("appointment")
                );

                card.setDate(
                    rs.getDate("date").toString()
                );
                
                card.setIcon(
                    rs.getString("icon")
                );

                P_CardFlow.add(card);
            }

            P_CardFlow.revalidate();
            P_CardFlow.repaint();

        } catch (Exception e) {

            System.out.println(e);
        }
    }
    
    public String formatKeHariBulan(String tanggalInput) {
        try {
            LocalDate tanggal = LocalDate.parse(tanggalInput);
            DateTimeFormatter formatterBaru = DateTimeFormatter.ofPattern("d MMM", Locale.ENGLISH);
            return tanggal.format(formatterBaru);
        } catch (Exception e) {
            System.out.println("Gagal convert tanggal: " + e.getMessage());
            return tanggalInput; // Kembalikan teks asli jika gagal parse
        }
    }
    
    private void setUkuranLokasi(){
        // Ambil ukuran layar user (monitor)
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.pack();
        
        int frameWidth = this.getSize().width;
        System.out.println(frameWidth);
        System.out.println(this.getSize().height);

        // Hitung posisi X agar mepet ke kanan
        int x = screenSize.width - frameWidth;
        int y = 0; // 0 berarti mepet ke atas

        this.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_TambahIngatan;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel L_Tanggal;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel P_CardFlow;
    private javax.swing.JScrollPane P_CardFlow3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
