/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author nabil
 */
public class mood_form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mood_form.class.getName());

    /**
     * Creates new form mood_form
     */
    public mood_form() {
        initComponents();
        
        setIconMood("bangga");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setIconMood(String text) {
        URL url = getClass().getResource("/Frames/images/mood/" + text + ".png");
        ImageIcon icon;

        if (url != null) {
            icon = new ImageIcon(url);
        } else {
            // coba fallback ke default
            url = getClass().getResource("/Frames/images/mood/bangga.png");
            icon = (url != null) ? new ImageIcon(url)
                                 : null; // atau ikon default alternatif
        }

        iconLabel.setIcon(icon);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        moodinput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        simpan_mood = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        iconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 225, 225));
        setResizable(false);

        Background.setBackground(new java.awt.Color(234, 227, 227));
        Background.setMaximumSize(new java.awt.Dimension(400, 330));
        Background.setMinimumSize(new java.awt.Dimension(400, 330));
        Background.setPreferredSize(new java.awt.Dimension(400, 330));

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        Navbar.setPreferredSize(new java.awt.Dimension(400, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout1.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout1);

        jPanel1.setMaximumSize(null);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INGETIN");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("21 Mei, 09:00");
        jLabel9.setPreferredSize(new java.awt.Dimension(260, 20));
        jPanel1.add(jLabel9);

        Navbar.add(jPanel1);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel7.setText("Icon");

        moodinput.setBackground(new java.awt.Color(234, 227, 227));
        moodinput.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        moodinput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel8.setText("Tuliskan mood kamu");

        simpan_mood.setBackground(new java.awt.Color(234, 227, 227));
        simpan_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        simpan_mood.setText("Simpan Mood");
        simpan_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        simpan_mood.addActionListener(this::simpan_moodActionPerformed);

        jComboBox1.setBackground(new java.awt.Color(234, 227, 227));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangga", "Bersalah", "Bingung", "Bosan", "Cemas", "Nyaman", "Frustasi", "Inspirasi", "Kaget", "Kepo", "Kewalahan", "Marah", "Melamun", "Mimpi", "Musisi", "Nakal", "Nostalgia", "Santai", "Sakit", "Semangat", "Malu", "Siap", "Stres", "Bersyukur", "Tenang", "Tidur" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox1.setMinimumSize(new java.awt.Dimension(72, 31));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(moodinput, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(simpan_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)))
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconLabel))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addComponent(iconLabel))
                        .addGap(4, 4, 4)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moodinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(simpan_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_moodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_moodActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:  
        String mood = jComboBox1.getSelectedItem().toString().toLowerCase();
        setIconMood(mood);

//        if (mood.equals("Bangga")) {
//            setIconMood("bangga");
//        }
//
//        else if (mood.equals("Bersalah")) {
//            setIconMood("bersalah");
//        }
//
//        else if (mood.equals("Bingung")) {
//            setIconMood("bingung");
//        }
//
//        else if (mood.equals("Bosan")) {
//            setIconMood("bored");
//        }
//
//        else if (mood.equals("Cemas")) {
//            setIconMood("cemas");
//        }
//
//        else if (mood.equals("Nyaman")) {
//            setIconMood("comfy");
//        }
//
//        else if (mood.equals("Frustasi")) {
//            setIconMood("frustasi");
//        }
//
//        else if (mood.equals("Inspirasi")) {
//            setIconMood("inspired");
//        }
//
//        else if (mood.equals("Kaget")) {
//            setIconMood("kaget");
//        }
//
//        else if (mood.equals("Kepo")) {
//            setIconMood("kepo");
//        }
//
//        else if (mood.equals("Kewalahan")) {
//            setIconMood("kewalahan");
//        }
//
//        else if (mood.equals("Marah")) {
//            setIconMood("marah");
//        }
//
//        else if (mood.equals("Melamun")) {
//            setIconMood("melamun");
//        }
//
//        else if (mood.equals("Mimpi")) {
//            setIconMood("mimpi");
//        }
//
//        else if (mood.equals("Musisi")) {
//            setIconMood("musisi");
//        }
//
//        else if (mood.equals("Nakal")) {
//            setIconMood("nakal");
//        }
//
//        else if (mood.equals("Nostalgia")) {
//            setIconMood("nostalgia");
//        }
//
//        else if (mood.equals("Santai")) {
//            setIconMood("nyantai");
//        }
//
//        else if (mood.equals("Sakit")) {
//            setIconMood("sakit");
//        }
//
//        else if (mood.equals("Semangat")) {
//            setIconMood("semangat");
//        }
//
//        else if (mood.equals("Malu")) {
//            setIconMood("shy");
//        }
//
//        else if (mood.equals("Siap")) {
//            setIconMood("siap");
//        }
//
//        else if (mood.equals("Stres")) {
//            setIconMood("stres");
//        }
//
//        else if (mood.equals("Bersyukur")) {
//            setIconMood("syukur");
//        }
//
//        else if (mood.equals("Tenang")) {
//            setIconMood("tenang");
//        }
//
//        else if (mood.equals("Tidur")) {
//            setIconMood("turu");
//        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mood_form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField moodinput;
    private javax.swing.JButton simpan_mood;
    // End of variables declaration//GEN-END:variables
}
