/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import KoneksiDB.MotivasiDB;
import java.awt.HeadlessException;
import java.net.URL;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class motivasi_form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(motivasi_form.class.getName());
    private MotivasiDB database_motivasi;
    private static int id = 0;
    
    /**
     * Creates new form motivasi_form
     */
    public motivasi_form(int id_motivasi) {
        initComponents();
        
        database_motivasi = new MotivasiDB();
        
        id = id_motivasi;
        if(id != 0) {
            setData();
        }
        
        setUkuranLokasi();
        
        updateWaktu();
        Timer timer = new Timer(60000, e -> updateWaktu());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        isi_navbar = new javax.swing.JPanel();
        BTN_Back = new javax.swing.JLabel();
        AppName = new javax.swing.JLabel();
        L_Hour = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        Label1 = new javax.swing.JLabel();
        simpan_motivasi = new javax.swing.JButton();
        Label2 = new javax.swing.JLabel();
        parameter_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(234, 227, 227));
        Background.setMaximumSize(new java.awt.Dimension(400, 330));
        Background.setMinimumSize(new java.awt.Dimension(400, 330));

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        Navbar.setPreferredSize(new java.awt.Dimension(400, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout1.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout1);

        isi_navbar.setMaximumSize(null);
        isi_navbar.setOpaque(false);
        isi_navbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        BTN_Back.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        BTN_Back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        BTN_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_BackMouseClicked(evt);
            }
        });
        isi_navbar.add(BTN_Back);

        AppName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppName.setText("INGETIN");
        AppName.setToolTipText("");
        AppName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AppName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppNameMouseClicked(evt);
            }
        });
        isi_navbar.add(AppName);

        L_Hour.setBackground(new java.awt.Color(0, 0, 0));
        L_Hour.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        L_Hour.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L_Hour.setText("21 Mei, 09:00");
        L_Hour.setPreferredSize(new java.awt.Dimension(260, 20));
        isi_navbar.add(L_Hour);

        Navbar.add(isi_navbar);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        iconLabel.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N

        name_input.setBackground(new java.awt.Color(234, 227, 227));
        name_input.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        name_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Label1.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        Label1.setText("Tuliskan kata-kata motivasi kamu");

        simpan_motivasi.setBackground(new java.awt.Color(234, 227, 227));
        simpan_motivasi.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        simpan_motivasi.setText("Simpan Motivasi");
        simpan_motivasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        simpan_motivasi.addActionListener(this::simpan_motivasiActionPerformed);

        Label2.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        Label2.setText("Pada parameter berapa motivasi ini ditampilkan?");

        parameter_input.setBackground(new java.awt.Color(234, 227, 227));
        parameter_input.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        parameter_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLabel)
                        .addGap(24, 24, 24))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label2)
                            .addComponent(parameter_input, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpan_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Label1)
                        .addGap(7, 7, 7)
                        .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconLabel)
                        .addGap(14, 14, 14)
                        .addComponent(Label2)
                        .addGap(7, 7, 7)
                        .addComponent(parameter_input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpan_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_BackMouseClicked
        back();
    }//GEN-LAST:event_BTN_BackMouseClicked

    private void AppNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppNameMouseClicked
        back();
    }//GEN-LAST:event_AppNameMouseClicked

    private void simpan_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_motivasiActionPerformed
        try {
            String nama = name_input.getText();
            int parameter = Integer.parseInt(parameter_input.getText());
        
            if(id == 0){
                database_motivasi.tambahMotivasi(nama, parameter);
            }else{
                database_motivasi.updateMotivasi(id, nama, parameter);
            }
            
            table_motivasi FTableMotivasi = new table_motivasi();
            FTableMotivasi.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_simpan_motivasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new motivasi_form(0).setVisible(true));
    }
    
    private void setData(){
        try {
            ResultSet motivasi = database_motivasi.cariMotivasi(id);
            if (motivasi != null && motivasi.next()) { 
                name_input.setText(motivasi.getString("name"));
                parameter_input.setText(String.valueOf(motivasi.getInt("parameter")));
            } else {
                System.out.println("Data motivasi dengan ID tersebut tidak ditemukan.");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }   
    }

    private void setUkuranLokasi(){
        // Ambil ukuran layar user (monitor)
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.pack();
        
        int frameWidth = this.getSize().width;
        System.out.println(frameWidth);
        System.out.println(this.getSize().height);

        // Hitung posisi X agar mepet ke kanan
        int x = screenSize.width - frameWidth;
        int y = 0; // 0 berarti mepet ke atas

        this.setLocation(x, y);
    }
    
     private void back(){
        table_motivasi FTableMotivasi = new table_motivasi();
        FTableMotivasi.setVisible(true);
        this.dispose();
    }
     
    public LocalTime waktu;
    private void updateWaktu(){
         LocalDateTime sekarang = LocalDateTime.now();
         L_Hour.setText(sekarang.format(DateTimeFormatter.ofPattern("dd MMMM, HH:mm")));
         waktu = LocalTime.now();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppName;
    private javax.swing.JLabel BTN_Back;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel L_Hour;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel isi_navbar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField name_input;
    private javax.swing.JTextField parameter_input;
    private javax.swing.JButton simpan_motivasi;
    // End of variables declaration//GEN-END:variables
}
