/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Edella
 */
public class P_CardJanji extends javax.swing.JPanel {

    /**
     * Creates new form P_CardJanji2
     */
    public P_CardJanji() {
        initComponents();
    }

    public void setTitle(String text) {
        LB_Title.setText(text);
    }

    public void setDate(String text) {
        LB_Date.setText(text);
    }
    
    public void setIcon(String text) {
        URL url = getClass().getResource("/Frames/images/mood/" + text + ".png");
        ImageIcon icon;

        if (url != null) { icon = new ImageIcon(url);
        } else {
            icon = new ImageIcon(
                getClass().getResource("/Frames/images/mood/bangga.png")
            );
        }
        
        LB_Icon.setIcon(icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        LB_Icon = new javax.swing.JLabel();
        LB_Title = new javax.swing.JLabel();
        LB_Date = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 227, 227));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(335, 35));
        setMinimumSize(new java.awt.Dimension(335, 35));
        setPreferredSize(new java.awt.Dimension(335, 35));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        add(jCheckBox1);

        LB_Icon.setForeground(new java.awt.Color(0, 0, 0));
        LB_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Atur Mood.png"))); // NOI18N
        add(LB_Icon);

        LB_Title.setForeground(new java.awt.Color(0, 0, 0));
        LB_Title.setText("jLabel1");
        add(LB_Title);

        LB_Date.setForeground(new java.awt.Color(0, 0, 0));
        LB_Date.setText("jLabel1");
        add(LB_Date);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Date;
    private javax.swing.JLabel LB_Icon;
    private javax.swing.JLabel LB_Title;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
