/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class setting extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(setting.class.getName());

    /**
     * Creates new form setting
     */
    public setting() {
        initComponents();
        setUkuranLokasi();
                
        updateWaktu();
        Timer timer = new Timer(60000, e -> updateWaktu());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        atur_motivasi = new javax.swing.JButton();
        Navbar = new javax.swing.JPanel();
        isi_navbar = new javax.swing.JPanel();
        BTN_Back = new javax.swing.JLabel();
        AppName = new javax.swing.JLabel();
        L_Hour = new javax.swing.JLabel();
        desain_setting = new javax.swing.JPanel();
        IMG_Atur = new javax.swing.JLabel();
        text_bubble2 = new javax.swing.JLabel();
        IMG_Bubble = new javax.swing.JLabel();
        text_bubble1 = new javax.swing.JLabel();
        atur_mood = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("setting");

        Background.setBackground(new java.awt.Color(233, 225, 225));
        Background.setPreferredSize(new java.awt.Dimension(400, 330));

        atur_motivasi.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        atur_motivasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Atur Motivasi.png"))); // NOI18N
        atur_motivasi.setText("Atur Motivasi");
        atur_motivasi.setToolTipText("");
        atur_motivasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atur_motivasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        atur_motivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atur_motivasiMouseClicked(evt);
            }
        });
        atur_motivasi.addActionListener(this::atur_motivasiActionPerformed);

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        Navbar.setPreferredSize(new java.awt.Dimension(400, 60));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout3.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout3);

        isi_navbar.setMaximumSize(null);
        isi_navbar.setOpaque(false);
        isi_navbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        BTN_Back.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        BTN_Back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        BTN_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_BackMouseClicked(evt);
            }
        });
        isi_navbar.add(BTN_Back);

        AppName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppName.setText("INGETIN");
        AppName.setToolTipText("");
        AppName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AppName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppNameMouseClicked(evt);
            }
        });
        isi_navbar.add(AppName);

        L_Hour.setBackground(new java.awt.Color(0, 0, 0));
        L_Hour.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        L_Hour.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L_Hour.setText("21 Mei, 09:00");
        L_Hour.setPreferredSize(new java.awt.Dimension(260, 20));
        isi_navbar.add(L_Hour);

        Navbar.add(isi_navbar);

        desain_setting.setOpaque(false);
        desain_setting.setLayout(null);

        IMG_Atur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/IMG_Atur.png"))); // NOI18N
        desain_setting.add(IMG_Atur);
        IMG_Atur.setBounds(120, 60, 159, 87);

        text_bubble2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        text_bubble2.setForeground(new java.awt.Color(51, 0, 88));
        text_bubble2.setText("dan mood kamu!");
        text_bubble2.setAlignmentY(0.1F);
        text_bubble2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text_bubble2.setMinimumSize(new java.awt.Dimension(270, 21));
        text_bubble2.setRequestFocusEnabled(false);
        desain_setting.add(text_bubble2);
        text_bubble2.setBounds(40, 40, 92, 40);

        IMG_Bubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/IMG_Bubble.png"))); // NOI18N
        desain_setting.add(IMG_Bubble);
        IMG_Bubble.setBounds(10, 10, 170, 90);

        text_bubble1.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        text_bubble1.setForeground(new java.awt.Color(51, 0, 88));
        text_bubble1.setText("Yuk atur motivasi");
        text_bubble1.setAlignmentY(0.1F);
        text_bubble1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text_bubble1.setMinimumSize(new java.awt.Dimension(270, 21));
        text_bubble1.setRequestFocusEnabled(false);
        desain_setting.add(text_bubble1);
        text_bubble1.setBounds(50, 30, 92, 40);

        atur_mood.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        atur_mood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Atur Mood.png"))); // NOI18N
        atur_mood.setText("Atur Mood");
        atur_mood.setToolTipText("");
        atur_mood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atur_mood.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        atur_mood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atur_moodMouseClicked(evt);
            }
        });
        atur_mood.addActionListener(this::atur_moodActionPerformed);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(atur_motivasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atur_mood))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(desain_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(434, 434, 434)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(atur_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atur_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(desain_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atur_motivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atur_motivasiMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_atur_motivasiMouseClicked

    private void atur_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atur_motivasiActionPerformed
        table_motivasi FTableMotivasi = new table_motivasi();
        FTableMotivasi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atur_motivasiActionPerformed

    private void BTN_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_BackMouseClicked
        back();
    }//GEN-LAST:event_BTN_BackMouseClicked

    private void AppNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppNameMouseClicked
        back();
    }//GEN-LAST:event_AppNameMouseClicked

    private void atur_moodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atur_moodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atur_moodMouseClicked

    private void atur_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atur_moodActionPerformed
        // TODO add your handling code here:
        table_mood FTableMood = new table_mood();
        FTableMood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atur_moodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new setting().setVisible(true));
    }
    
    private void setUkuranLokasi(){
        // Ambil ukuran layar user (monitor)
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.pack();
        
        int frameWidth = this.getSize().width;
        System.out.println(frameWidth);
        System.out.println(this.getSize().height);

        // Hitung posisi X agar mepet ke kanan
        int x = screenSize.width - frameWidth;
        int y = 0; // 0 berarti mepet ke atas

        this.setLocation(x, y);
    }
    
    private void back(){
        Kalender FKalender = new Kalender();
        FKalender.setVisible(true);
        this.dispose();
    }
    
    public LocalTime waktu;
    private void updateWaktu(){
         LocalDateTime sekarang = LocalDateTime.now();
         L_Hour.setText(sekarang.format(DateTimeFormatter.ofPattern("dd MMMM, HH:mm")));
         waktu = LocalTime.now();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppName;
    private javax.swing.JLabel BTN_Back;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel IMG_Atur;
    private javax.swing.JLabel IMG_Bubble;
    private javax.swing.JLabel L_Hour;
    private javax.swing.JPanel Navbar;
    private javax.swing.JButton atur_mood;
    private javax.swing.JButton atur_motivasi;
    private javax.swing.JPanel desain_setting;
    private javax.swing.JPanel isi_navbar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel text_bubble1;
    private javax.swing.JLabel text_bubble2;
    // End of variables declaration//GEN-END:variables
}
