/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author ASUS
 */
public class table_motivasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(table_motivasi.class.getName());

    /**
     * Creates new form table_motivasi
     */
    public table_motivasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMotivasi = new javax.swing.JTable();
        Navbar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BTN_Back = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cari_motivasi = new javax.swing.JButton();
        tambah_motivasi = new javax.swing.JButton();
        update_motivasi = new javax.swing.JButton();
        hapus_motivasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableMotivasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Icon", "Tittle"
            }
        ));
        jScrollPane1.setViewportView(tableMotivasi);

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        Navbar.setPreferredSize(new java.awt.Dimension(400, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout1.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout1);

        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 24));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 24));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        BTN_Back.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        BTN_Back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        jPanel1.add(BTN_Back);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INGETIN");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("21 Mei, 09:00");
        jLabel9.setPreferredSize(new java.awt.Dimension(420, 20));
        jPanel1.add(jLabel9);

        Navbar.add(jPanel1);

        cari_motivasi.setBackground(new java.awt.Color(234, 227, 227));
        cari_motivasi.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        cari_motivasi.setText("Cari motivasi");
        cari_motivasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cari_motivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cari_motivasiMouseClicked(evt);
            }
        });
        cari_motivasi.addActionListener(this::cari_motivasiActionPerformed);

        tambah_motivasi.setBackground(new java.awt.Color(234, 227, 227));
        tambah_motivasi.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        tambah_motivasi.setText("Tambah motivasi");
        tambah_motivasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tambah_motivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_motivasiMouseClicked(evt);
            }
        });
        tambah_motivasi.addActionListener(this::tambah_motivasiActionPerformed);

        update_motivasi.setBackground(new java.awt.Color(234, 227, 227));
        update_motivasi.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        update_motivasi.setText("Update motivasi");
        update_motivasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        update_motivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_motivasiMouseClicked(evt);
            }
        });
        update_motivasi.addActionListener(this::update_motivasiActionPerformed);

        hapus_motivasi.setBackground(new java.awt.Color(234, 227, 227));
        hapus_motivasi.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        hapus_motivasi.setText("Hapus motivasi");
        hapus_motivasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hapus_motivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapus_motivasiMouseClicked(evt);
            }
        });
        hapus_motivasi.addActionListener(this::hapus_motivasiActionPerformed);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel1.setText("KUMPULAN MOTIVASI KAMU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambah_motivasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cari_motivasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_motivasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cari_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tambah_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapus_motivasi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_motivasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_motivasiActionPerformed

    private void hapus_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_motivasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus_motivasiActionPerformed

    private void cari_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_motivasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_motivasiActionPerformed

    private void cari_motivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cari_motivasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_motivasiMouseClicked

    private void tambah_motivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_motivasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah_motivasiActionPerformed

    private void tambah_motivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_motivasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah_motivasiMouseClicked

    private void update_motivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_motivasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_motivasiMouseClicked

    private void hapus_motivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapus_motivasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus_motivasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new table_motivasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTN_Back;
    private javax.swing.JPanel Navbar;
    private javax.swing.JButton cari_motivasi;
    private javax.swing.JButton hapus_motivasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMotivasi;
    private javax.swing.JButton tambah_motivasi;
    private javax.swing.JButton update_motivasi;
    // End of variables declaration//GEN-END:variables
}
