/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import KoneksiDB.Koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nabil
 */
public class table_mood extends javax.swing.JFrame {
    Koneksi kon;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(table_mood.class.getName());

    /**
     * Creates new form table_mood
     */
    public table_mood() {
        initComponents();
        kon = new Koneksi();
        
        tampilSemuaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMood = new javax.swing.JTable();
        cari_mood = new javax.swing.JButton();
        tampil_mood = new javax.swing.JButton();
        update_mood = new javax.swing.JButton();
        hapus_mood = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cariID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tambah_mood = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 227, 227));
        setPreferredSize(new java.awt.Dimension(600, 580));

        jPanel3.setBackground(new java.awt.Color(234, 227, 227));
        jPanel3.setName("kumpulan mood"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(580, 400));

        Navbar.setBackground(new java.awt.Color(215, 182, 244));
        Navbar.setMaximumSize(null);
        Navbar.setPreferredSize(new java.awt.Dimension(400, 60));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 18);
        flowLayout3.setAlignOnBaseline(true);
        Navbar.setLayout(flowLayout3);

        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 24));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 24));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 13, 0));

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/images/BTN_Back.png"))); // NOI18N
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INGETIN");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 17)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("21 Mei, 09:00");
        jLabel9.setPreferredSize(new java.awt.Dimension(420, 20));
        jPanel1.add(jLabel9);

        Navbar.add(jPanel1);

        tableMood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Icon", "Tittle"
            }
        ));
        jScrollPane1.setViewportView(tableMood);

        cari_mood.setBackground(new java.awt.Color(234, 227, 227));
        cari_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        cari_mood.setText("Cari data mood");
        cari_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cari_mood.addActionListener(this::cari_moodActionPerformed);

        tampil_mood.setBackground(new java.awt.Color(234, 227, 227));
        tampil_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        tampil_mood.setText("Tampil data mood");
        tampil_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tampil_mood.addActionListener(this::tampil_moodActionPerformed);

        update_mood.setBackground(new java.awt.Color(234, 227, 227));
        update_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        update_mood.setText("Update data mood");
        update_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        update_mood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_moodMouseClicked(evt);
            }
        });
        update_mood.addActionListener(this::update_moodActionPerformed);

        hapus_mood.setBackground(new java.awt.Color(234, 227, 227));
        hapus_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        hapus_mood.setText("Hapus data mood");
        hapus_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hapus_mood.addActionListener(this::hapus_moodActionPerformed);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel1.setText("KUMPULAN MOOD KAMU");

        cariID.addActionListener(this::cariIDActionPerformed);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Cari mood kamu berdasarkan  ID");

        tambah_mood.setBackground(new java.awt.Color(234, 227, 227));
        tambah_mood.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        tambah_mood.setText("Tambah data mood");
        tambah_mood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tambah_mood.addActionListener(this::tambah_moodActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tampil_mood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari_mood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_mood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapus_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah_mood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cari_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cariID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tampil_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambah_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapus_mood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_moodActionPerformed
        // TODO add your handling code here
        int row = tableMood.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
            return;
        }
        
        String id = tableMood.getValueAt(row,0).toString();
        
         updateMood form =  new updateMood(id);
         
         form.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_update_moodActionPerformed

    private void hapus_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_moodActionPerformed
        // TODO add your handling code here
        int row = tableMood.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Pilih data yang mau di hapus");
            
            return;
        }
        
        String id = tableMood.getValueAt(row, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(confirm==0){
            try{
                Statement st = kon.con.createStatement();
                
                String sql = "DELETE FROM db_ingetin" + "WHERE id='" + id + "'";
                
                st.executeUpdate(sql);
                
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                
                tampilSemuaData();
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_hapus_moodActionPerformed

    private void update_moodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_moodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_moodMouseClicked

    private void cari_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_moodActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_cari_moodActionPerformed

    private void tambah_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_moodActionPerformed
        // TODO add your handling code here:
        tambahMood form = new tambahMood();
        
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tambah_moodActionPerformed

    private void cariIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariIDActionPerformed

    private void tampil_moodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampil_moodActionPerformed
        // TODO add your handling code here:
        tampilSemuaData();
    }//GEN-LAST:event_tampil_moodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new table_mood().setVisible(true));
    }
    
    public void tampilSemuaData(){
        Object header[] ={"ID","Icon","Tittle"};
        
        DefaultTableModel data = new DefaultTableModel(null, header);
        
        tableMood.setModel(data);
        try{
            Statement st = kon.con.createStatement();
            ResultSet rs =  st.executeQuery("SELECT * FROM db_ingetin");
            
            while(rs.next()){
                String row[] = {rs.getString("id"), rs.getString("icon"), rs.getString("tittle")};
                data.addRow(row);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        };
    }
    
    public void cariData(){
        Object header[] = {"ID","Icon","Tittle"};
         DefaultTableModel data = new DefaultTableModel(null, header);
         
         tableMood.setModel(data);
         
         String cari = cariID.getText();
         
         try{
         
            Statement st = kon.con.createStatement();
            String sql = "SELECT * FROM db_ingrtin" + "WHERE id LIKE '%" + cari +"%'";
             
            ResultSet rs = st.executeQuery(sql);
             
            while(rs.next()){
                String row[] = {rs.getString("id"), rs.getString("icon"), rs.getString("tittle")};
                
                data.addRow(row);
            }
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navbar;
    private javax.swing.JTextField cariID;
    private javax.swing.JButton cari_mood;
    private javax.swing.JButton hapus_mood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tableMood;
    private javax.swing.JButton tambah_mood;
    private javax.swing.JButton tampil_mood;
    private javax.swing.JButton update_mood;
    // End of variables declaration//GEN-END:variables
}
